name: Check for artifact and register release

on:
  workflow_run:
    workflows: ["Maven Release"]
    types:
      - completed

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-check-and-register-release.yml@v2.1.8
    if:  "${{ github.event.workflow_run.conclusion == 'success' }}"
    with:
      artifact-pattern: "octopus/releng/releng-lib/_VER_/releng-lib-_VER_.jar"
    secrets: inherit
